# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{petfinder}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Hutzelman"]
  s.date = %q{2010-07-09}
  s.description = %q{Ruby gem wrapper for the Petfinder API}
  s.email = %q{ehutzelman@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/petfinder.rb",
     "lib/petfinder/auth.rb",
     "lib/petfinder/breeds.rb",
     "lib/petfinder/client.rb",
     "lib/petfinder/pet.rb",
     "lib/petfinder/shelter.rb",
     "petfinder.gemspec",
     "spec/fixtures/auth.xml",
     "spec/fixtures/breed_list.xml",
     "spec/fixtures/pet.xml",
     "spec/fixtures/pet_list.xml",
     "spec/fixtures/shelter.xml",
     "spec/fixtures/shelter_list.xml",
     "spec/petfinder_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/ehutzelman/petfinder}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby gem wrapper for the Petfinder API}
  s.test_files = [
    "spec/petfinder_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<happymapper>, [">= 0.3.2"])
      s.add_runtime_dependency(%q<httparty>, [">= 0.5.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.5"])
    else
      s.add_dependency(%q<happymapper>, [">= 0.3.2"])
      s.add_dependency(%q<httparty>, [">= 0.5.0"])
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.5"])
    end
  else
    s.add_dependency(%q<happymapper>, [">= 0.3.2"])
    s.add_dependency(%q<httparty>, [">= 0.5.0"])
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.5"])
  end
end

